# Generated by Django 4.2 on 2025-05-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_delete_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=20)),
                ("comment", models.CharField(max_length=70)),
                ("send_date", models.DateField(auto_now_add=True)),
                ("lastname", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "CustomerMessage",
                "verbose_name_plural": "Customers Message",
            },
        ),
    ]
