# Generated by Django 4.2 on 2025-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_background_alter_contact_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='founder',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='founder/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='founder',
            name='bio',
            field=models.CharField(max_length=70),
        ),
    ]
