# Generated by Django 4.2 on 2025-05-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customermessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermessage",
            name="comment",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="founder",
            name="bio",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="founder",
            name="position",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
