# Generated by Django 4.2 on 2025-05-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_partner_options_founder_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
