# Generated by Django 4.2 on 2025-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_customermessage_comment_alter_founder_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
