# Generated by Django 4.2 on 2025-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='null', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='cdcdbcjdc', max_length=20),
            preserve_default=False,
        ),
    ]
